[firebase]
web_api_key = "AIzaSyAkqgYgw4DU4vnvutH8W2y0qjYSy4RqvKc"
web_auth_domain = "studyhub-4066a.firebaseapp.com"
web_project_id = "studyhub-4066a"
web_app_id = "1:1009543227841:web:18c02f131de762b5cda740"